# Generated by Django 4.0.5 on 2022-07-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_allmails_id_alter_primary_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snoozed',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
